"""BL-01 — the Phase 0 compatibility golden suite.

Every declared public output of the portable core (CLI help, the plan-only plan, the
execute/push denials, the fail-closed error paths, ``--status``, a representative schema-v2
``run.json``, the pre-transition diagnostic, the executor/verifier envelopes, and the
exit-code table) is regenerated by :mod:`tests.compat_goldens` and compared byte-for-byte
against the reviewed fixture in ``tests/goldens/compatibility/``.

If a fixture is stale, that is a compatibility decision, not a test bug: review the diff,
and only then regenerate with ``python -m tests.compat_goldens --write``. The goldens are
never updated automatically during a later refactor.
"""

from __future__ import annotations

import re
import socket
import unittest
from pathlib import Path
from unittest.mock import patch

from pipeline_core.reports import ENVELOPE_KEYS, STATUS_TOKENS
from pipeline_core.state import SCHEMA_VERSION, VERDICT_TOKENS

from tests import compat_goldens as harness

GOLDEN_DIR = harness.GOLDEN_DIR
NORMALIZATIONS = GOLDEN_DIR / "NORMALIZATIONS.md"

#: The exit-code contract this baseline freezes (scripts/README.md, MI-01 table):
#: 10 ok / a delivery gate is pending, 20 blocked, 30 error, 1 push refused, 0 only for
#: the read-only --status inspector.
EXPECTED_EXIT_CODES = {
    "cli-help": 0,
    "plan-only-plan": 10,
    "denial-execute-plan-gate": 10,
    "denial-push": 1,
    "error-unknown-task-type": 30,
    "error-absolute-logical-path": 30,
    "blocked-unmet-dependency": 20,
    "status-no-recorded-run": 0,
}


class GoldenComparisonTests(unittest.TestCase):
    """Each regenerated capture equals its reviewed fixture."""

    def test_every_declared_public_output_matches_its_reviewed_golden(self) -> None:
        produced = harness.regenerate()
        for name, text in sorted(produced.items()):
            with self.subTest(golden=name):
                path = GOLDEN_DIR / name
                self.assertTrue(path.is_file(), f"missing reviewed golden {name}")
                self.assertEqual(
                    path.read_text(encoding="utf-8"), text,
                    f"{name} drifted from its reviewed fixture; review the diff, then "
                    f"`python -m tests.compat_goldens --write` if the change is accepted",
                )

    def test_no_reviewed_golden_is_unaccounted_for(self) -> None:
        produced = set(harness.regenerate())
        on_disk = {p.name for p in GOLDEN_DIR.iterdir()
                   if p.is_file() and p.name != "NORMALIZATIONS.md"}
        self.assertEqual(on_disk, produced)


class DeterminismTests(unittest.TestCase):
    def test_regeneration_is_byte_identical_across_two_runs(self) -> None:
        self.assertEqual(harness.regenerate(), harness.regenerate())


class RedactionTests(unittest.TestCase):
    def _host_needles(self) -> list[str]:
        needles = [str(Path.home()), str(Path.home().resolve()), socket.gethostname()]
        return [n for n in needles if n]

    def test_generic_runner_word_is_not_treated_as_a_host_leak(self) -> None:
        with patch("tests.test_compatibility_goldens.socket.gethostname", return_value="host"):
            self.assertNotIn("runner", self._host_needles())

    def test_anchor_rules_normalize_windows_short_path_spelling(self) -> None:
        long_root = Path(r"C:\Users\runneradmin\AppData\Local\Temp\compat\project")
        short_root = Path(r"C:\Users\RUNNER~1\AppData\Local\Temp\compat\project")
        def variants(path: Path) -> tuple[Path, ...]:
            return (long_root, short_root) if path == short_root else (path,)

        with patch("tests.compat_goldens.path_variants", side_effect=variants):
            rules = harness._anchor_rules(
                project_root=short_root,
                agents_root=Path(r"C:\agents"),
                core_root=Path(r"C:\core"),
                workdir=Path(r"C:\work"),
            )
        self.assertEqual(
            harness._normalize(str(long_root / "profile.json"), rules),
            r"<project_root>\profile.json",
        )

    def test_no_golden_leaks_a_host_path_user_or_machine_name(self) -> None:
        needles = self._host_needles()
        for name, text in harness.regenerate().items():
            for needle in needles:
                self.assertNotIn(needle, text, f"{name} leaked {needle!r}")

    def test_captures_reference_only_logical_anchor_tokens(self) -> None:
        for name, text in harness.regenerate().items():
            for raw in ("AppData", "/tmp/", "\\Temp\\", "Syncthing"):
                self.assertNotIn(raw, text, f"{name} leaked {raw!r}")

    def test_nondeterministic_values_are_normalized_out(self) -> None:
        state = harness.regenerate()["run-state-v2.json"]
        self.assertIn('"run_id": "<run-id>"', state)
        self.assertIn("<timestamp>", state)
        self.assertNotRegex(state, re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}[:-]\d{2}"))


class ExitCodeContractTests(unittest.TestCase):
    def test_exit_code_table_matches_the_frozen_contract(self) -> None:
        rows = dict(
            line.split(": ", 1)
            for line in harness.load_golden("exit-code-table.txt").splitlines() if line
        )
        observed = {name: int(code) for name, code in rows.items()}
        self.assertEqual(observed, EXPECTED_EXIT_CODES)

    def test_push_denial_message_is_frozen_verbatim(self) -> None:
        text = harness.load_golden("denial-push.txt")
        self.assertIn("exit: 1", text)
        self.assertIn(
            "push is denied at this stage and the runner has no push code path.", text)
        self.assertNotIn("run.json", text)

    def test_plan_only_plan_carries_the_full_c1_to_c8_shape(self) -> None:
        text = harness.load_golden("plan-only-plan.txt")
        for marker in ("C1.", "C2.", "C3.", "C4.", "C5.", "C6.", "C7.", "C8."):
            self.assertIn(marker, text)
        self.assertIn("C5. Exit code: 10 (a delivery gate is pending)", text)

    def test_execute_plan_gate_denial_writes_no_run_state(self) -> None:
        text = harness.load_golden("denial-execute-plan-gate.txt")
        self.assertIn("exit: 10", text)
        self.assertNotIn("run.json", text)


class EnvelopeContractTests(unittest.TestCase):
    """The frozen envelope goldens track the live contract constants."""

    def test_executor_status_envelope_keys_track_ENVELOPE_KEYS(self) -> None:
        import json
        envelope = json.loads(harness.load_golden("executor-status-envelope.json"))
        self.assertEqual(set(envelope), set(ENVELOPE_KEYS))
        self.assertIn(envelope["status"], STATUS_TOKENS)

    def test_verifier_verdict_envelope_tracks_the_verdict_tokens(self) -> None:
        import json
        envelope = json.loads(harness.load_golden("verifier-verdict-envelope.json"))
        self.assertEqual(set(envelope), {"verdict"})
        self.assertIn(envelope["verdict"], VERDICT_TOKENS)

    def test_run_state_golden_is_pinned_to_the_current_schema_version(self) -> None:
        import json
        state = json.loads(harness.load_golden("run-state-v2.json"))
        self.assertEqual(state["schema_version"], SCHEMA_VERSION)
        statuses = {task["status"] for task in state["tasks"]}
        self.assertEqual(statuses, {"pending", "implemented", "verified", "blocked"})


class NormalizationDocTests(unittest.TestCase):
    """AC-2: every golden has a documented source scenario and normalization."""

    def test_normalizations_doc_names_every_golden(self) -> None:
        self.assertTrue(NORMALIZATIONS.is_file(), "NORMALIZATIONS.md is missing")
        doc = NORMALIZATIONS.read_text(encoding="utf-8")
        for name in harness.regenerate():
            self.assertIn(name, doc, f"{name} has no entry in NORMALIZATIONS.md")

    def test_normalizations_doc_describes_each_normalization_rule(self) -> None:
        doc = NORMALIZATIONS.read_text(encoding="utf-8").lower()
        for rule in ("<timestamp>", "<run-id>", "<project_root>", "<agents_root>",
                     "<core_root>", "<workdir>", "duration"):
            self.assertIn(rule.lower(), doc, f"{rule} normalization is undocumented")


if __name__ == "__main__":
    unittest.main()
